# Generated by Django 3.1.7 on 2021-04-03 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 18, 8, 31, 295364, tzinfo=utc)),
        ),
    ]
