# Generated by Django 3.1.7 on 2021-04-03 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20210403_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approved_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='APP.staff'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 18, 36, 41, 212972, tzinfo=utc)),
        ),
    ]
