# Generated by Django 3.1.7 on 2021-04-04 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20210404_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classs',
        ),
        migrations.AddField(
            model_name='student',
            name='class1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 6, 43, 3, 47714, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='eventsregister',
            name='student',
        ),
        migrations.AddField(
            model_name='eventsregister',
            name='student',
            field=models.ManyToManyField(blank=True, to='APP.Student'),
        ),
    ]
