# Generated by Django 3.1.7 on 2021-04-04 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_auto_20210404_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 7, 21, 45, 315044, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, to='APP.Organizer'),
        ),
    ]
